# fly.toml app configuration file generated for meal-maverick on 2025-07-18T18:15:36-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meal-maverick'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
